export const BUILDING_COST = 10000;

export const BUILDING_NAMES = [
  'Bedroom',
  'Basement',
  'Small Office',
  'Large Office',
  'Building',
  'Office Park',
  'Skyscraper'
];

export const BUILDING_CAPACITIES = [
  1,
  5,
  25,
  50,
  100,
  500,
  1000
];

export const BUILDING_FLOOR_CAPACITY = 100;

export const BUILDING_LOCATIONS = [
  'Sausalito',
  'San Francisco',
  'Chicago',
  'New York',
  'Reykyavík',
  'Tokyo',
  'Liverpool',
  'Los Angeles',
  'Seoul',
  'Portland',
  'Seattle',
  'Las Vegas',
  'Santa Fe',
  'Austin',
  'Salt Lake City',
  'Denver',
  'Butte',
  'Kansas City',
  'Lawrence',
  'St. Louis',
  'Chicago',
  'Indianapolis',
  'Minneapolis',
  'Detroit',
  'New Orelans',
  'Miami',
  'Nashville',
  'Philadelphia',
  'Toronto',
  'Vancouver',
  'Ottowa',
  'Tiujana',
  'Mexico City',
  'London',
  'Nuuk',
  'Paris',
  'Barcelona',
  'Lisbon',
  'Brussels',
  'Amsterdam',
  'Luxembourg City',
  'Berlin',
  'Rome',
  'Vienna',
  'Warsaw',
  'Coppenhagen',
  'Oslo',
  'Stockholm',
  'Helsinki',
  'Tallinn',
  'Riga',
  'Vilnius',
  'Minsk',
  'Istanbul',
  'Dubai',
  'Cairo',
  'Freetown',
  'Lagos',
  'Kinshasa',
  'Luanda',
  'Nairobi',
  'Mogadishu',
  'Abidjan',
  'Alexandria',
  'Johannesburg',
  'New Delhi',
  'Kathmandu',
  'Ho Chi Minh City',
  'Bangkok',
  'Kuala Lumpur',
  'Jakarta',
  'Manila',
  'Perth',
  'Melbourne',
  'Sydney',
  'Auckland',
  'Lima',
  'São Paulo',
  'Buenos Aires',
  'Santiago',
  'Stanley',
  'Hong Kong',
  'Taipei',
  'Shanghai',
  'Beijing',
  'Osaka',
  'Sapporo',
  'Ulaanbaatar',
  'Moscow',
  'Antarctica',
  'The Moon',
  'Mercury',
  'Venus',
  'Mars',
  'Asteroid Belt',
  'Jupiter',
  'Saturn',
  'Uranus',
  'Neptune',
  'Pluto'
];

export const PEOPLE_COST = 1000;

export const PEOPLE_PROMOTION_COST = 1000;

export const PEOPLE_RANKS = [
  'Intern',
  'Sr. Intern',
  'Producer',
  'Sr. Producer',
  'Executive Producer',
  'Sr. Executive Producer',
  'VP of Producing',
  'Sr. VP of Producing',
  'Executive Sr. VP of Producing',
  'Immortal VP of Producing'
];

export const AD_RATE = [10000, 5000, 2500, 1000, 500, 250, 100, 50, 25, 1];
